- group: { name: future, enabled: true }
- group: { name: extra, enabled: true }
- group: { name: use-lens, enabled: true }
- group: { name: generalise, enabled: true }
- group: {name: partial, enabled: true}

- arguments: [ --cross, --refactor, --color, -XQuasiQuotes]
#- arguments: [ --cross, --color, -XQuasiQuotes]

- extensions:
  - default: true


# - ignore: { name: Avoid lambda }
# - ignore: { name: Redundant lambda }
# - ignore: { name: Redundant bracket }
- ignore: { name: Unused LANGUAGE pragma }
# - ignore: { name: Eta reduce }
- ignore: { name: Use camelCase }
# - ignore: { name: Use guards }
# - ignore: { name: Use fewer imports }
#- ignore: { name: Unused top binds }

# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
