#resolver: nightly-2024-01-17
#resolver: lts-21.25
resolver: lts-22.7

packages:
  - .

# extra-deps:
#   - vector-space-0.16@sha256:3b93ce68ceb96b173d472b17c89283e5a652a270a40b33f49d65d8b7dd4492e8,2016

ghc-options:
  "$everything": -haddock
# nix:
#   enable: true

#   # true by default. Should Nix run in a pure shell?
#   pure: true

#   # Unset by default. You cannot set this option if `packages:`
#   # is already present and not empty.
#   shell-file: shell.nix

#   # A list of strings, empty by default. Additional options that will be passed
#   # verbatim to the `nix-shell` command.
#   nix-shell-options: []

#   # A list of strings, empty by default, such as
#   # `[nixpkgs=/my/local/nixpkgs/clone]` that will be used to override
#   # NIX_PATH.
#   path: []

#   # false by default. Whether to add your Nix dependencies as Nix garbage
#   # collection roots. This way, calling nix-collect-garbage will not remove
#   # those packages from the Nix store, saving you some time when running
#   # stack build again with Nix support activated.
#   #
#   # This creates a `nix-gc-symlinks` directory in the project `.stack-work`.
#   # To revert that, just delete this `nix-gc-symlinks` directory.
#   add-gc-roots: false
