resolver: lts-22.15
#resolver: nightly-2024-04-10

packages:
  - .

# ghc-options:
#  "$locals": -prof -fprof-auto

#extra-deps:
# - haskell-dap-0.0.16.0@sha256:5ee4fba7ce1b8220f486a5251a941e6cd739ab2330e8f25efc5af553a4e1c61d,944

#ghc-options:
# "$everything": -O2

notify-if-nix-on-path: false
