resolver: nightly-2024-10-04
#resolver: lts-21.25

packages:
  - .

notify-if-nix-on-path: false
# ghc-options:
#  "$locals": -prof -fprof-auto

# ghc-options:
#   "$locals":  -ddump-to-file  -ddump-ds

extra-deps:
 - hsc3-0.20@sha256:4e34f7a544cb7c5bfbf21e351707e032dbf1db4e661edb47c40260594421fdf5,5823


#ghc-options:
# "$everything": -O2
