name: Build Workflow

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GHC
        run: |
          stack setup
          stack exec -- ghc --version  

      - name: Build 
        run: |
          stack build --no-run-benchmarks
