name: Build Workflow

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Install GHC
        run: |
          stack setup
          stack exec -- ghc --version  

      - name: Build
        run: |
          stack build --no-run-benchmarks

      # - name: Test
      #   run: |
      #     stack test
