name: Haskell Stack CI
on:
  push:
    branches: [ "main", "feature/**", "refactor/**" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest]  
      fail-fast: false  
    steps:
    - uses: actions/checkout@v4
    
    # Create stack's root directory first
    - name: Create Stack root
      run: |
        mkdir -p ~/.stack
        mkdir -p .stack-work

    - name: Setup Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        enable-stack: true
        stack-version: 'latest'
        stack-no-global: true

    # Cache stack's package index first
    - name: Cache Stack package index
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack/pantry
          ~/.stack/indices
        key: ${{ runner.os }}-stack-pantry-${{ hashFiles('stack.yaml') }}-v1
        
    # Cache global stack programs
    - name: Cache Stack programs
      uses: actions/cache@v3
      with:
        path: ~/.stack/programs
        key: ${{ runner.os }}-stack-programs-${{ hashFiles('stack.yaml') }}-v1

    # Cache project dependencies
    - name: Cache Stack project dependencies
      uses: actions/cache@v3
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('**/*.cabal', 'package.yaml', 'stack.yaml', 'stack.yaml.lock') }}-v1
        restore-keys: |
          ${{ runner.os }}-stack-work-

    # Initialize Stack with minimal operations
    - name: Initialize Stack
      run: |
        stack --version
        stack update --silent  # Update package index silently
        
    - name: Install GHC
      run: stack setup --install-ghc

    - name: Install dependencies
      run: |
        stack build --only-dependencies --test --bench --no-run-benchmarks

    - name: Build
      run: |
        stack build --test --bench --no-run-benchmarks --pedantic
        # --pedantic turns warnings into errors

    - name: Run tests
      run: |
        stack test --coverage
        stack hpc report .  # Generate coverage report
    
    - name: Install and run HLint
      run: |
        stack install hlint
        stack exec -- hlint .
    
    - name: Check formatting
      run: |
        stack install ormolu
        stack exec -- ormolu --mode check $(find . -name '*.hs')
    
    - name: Build documentation
      run: |
        stack haddock --no-haddock-deps
        # Optional: deploy docs to GitHub Pages

    - name: Run benchmarkse
      run: stack bench

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          .stack-work/dist/**/test-reports/
          .stack-work/dist/**/hpc/
          .stack-work/dist/**/doc/



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
