name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Setup Haskell
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '9.0.1' # Specify the GHC version
        cabal-version: '3.4'

    - name: Cache Stack
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/*.cabal', '**/stack.yaml', '**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Build project
      run: stack build --test --bench --no-run-tests --no-run-benchmarks

    - name: Run tests
      run: stack test

    # Optional: Add a step for linting if you're using HLint or a similar tool
    - name: Lint
      run: stack exec hlint .

    # Optional: Add steps for additional checks like code formatting
