name: Setup Workflow

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Stack root
        run: |
          mkdir -p ~/.stack
          mkdir -p .stack-work
      
      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8.2'
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
          
      - name: Install apply-refact
        run: stack build apply-refact
      
